import type { PrimitiveThemeTokens, SliderTokens } from "../types";

export function createSliderTokens(tokens: PrimitiveThemeTokens): SliderTokens {
  return {
    trackBorderRadius: tokens.radii.round,
    thumbBorderRadius: tokens.radii.round,
    valueBubbleBorderRadius: tokens.radii.md,
    valueBubbleBorderWidth: tokens.borderSize.sm,
    valueBubblePaddingHorizontal: tokens.space.xs,
    valueBubblePaddingVertical: tokens.space.xxs,
    valueBubbleGap: tokens.space.xxs,
    labelGap: tokens.space.xxs,
    layouts: {
      default: {
        reservedVerticalSpace: 0,
      },
      valueBubble: {
        reservedVerticalSpace: 28 + tokens.space.xxs,
      },
    },
    sizes: {
      small: {
        trackHeight: 4,
        thumbSize: 16,
        markSize: 6,
      },
      medium: {
        trackHeight: 6,
        thumbSize: 20,
        markSize: 6,
      },
      large: {
        trackHeight: 8,
        thumbSize: 24,
        markSize: 8,
      },
    },
    variants: {
      filled: {
        default: {
          activeMarkColor: tokens.colors.primary.value,
          activeTrackColor: tokens.colors.primary.value,
          inactiveTrackColor: tokens.colors.neutral["5"],
          labelColor: tokens.colors.primary.value,
          markColor: tokens.colors.neutral["6"],
          thumbBackgroundColor: tokens.colors.primary.value,
          thumbBorderColor: tokens.colors.primary.value,
          thumbBorderWidth: tokens.borderSize.sm,
          thumbHighlightColor: tokens.colors.primary.contrast,
          valueBubbleBackgroundColor: tokens.colors.primary.value,
          valueBubbleBorderColor: tokens.colors.primary.value,
          valueBubbleColor: tokens.colors.primary.contrast,
        },
        focused: {
          activeMarkColor: tokens.colors.primary.value,
          activeTrackColor: tokens.colors.primary.value,
          inactiveTrackColor: tokens.colors.neutral["5"],
          labelColor: tokens.colors.primary.value,
          markColor: tokens.colors.neutral["6"],
          thumbBackgroundColor: tokens.colors.primary.value,
          thumbBorderColor: tokens.colors.primary.value,
          thumbBorderWidth: tokens.borderSize.sm,
          thumbHighlightColor: tokens.colors.primary.contrast,
          valueBubbleBackgroundColor: tokens.colors.primary.value,
          valueBubbleBorderColor: tokens.colors.primary.value,
          valueBubbleColor: tokens.colors.primary.contrast,
        },
        disabled: {
          activeMarkColor: tokens.colors.neutral["6"],
          activeTrackColor: tokens.colors.neutral["5"],
          inactiveTrackColor: tokens.colors.neutral["5"],
          labelColor: tokens.colors.text.disabled,
          markColor: tokens.colors.neutral["6"],
          thumbBackgroundColor: tokens.colors.neutral["6"],
          thumbBorderColor: tokens.colors.neutral["6"],
          thumbBorderWidth: tokens.borderSize.sm,
          thumbHighlightColor: "transparent",
          valueBubbleBackgroundColor: tokens.colors.neutral["6"],
          valueBubbleBorderColor: tokens.colors.neutral["6"],
          valueBubbleColor: tokens.colors.text.disabled,
        },
      },
      outlined: {
        default: {
          activeMarkColor: tokens.colors.primary.value,
          activeTrackColor: tokens.colors.primary.value,
          inactiveTrackColor: tokens.colors.neutral["5"],
          labelColor: tokens.colors.primary.value,
          markColor: tokens.colors.neutral["6"],
          thumbBackgroundColor: tokens.colors.surface.elevated.value,
          thumbBorderColor: tokens.colors.primary.value,
          thumbBorderWidth: tokens.borderSize.md,
          thumbHighlightColor: "transparent",
          valueBubbleBackgroundColor: "transparent",
          valueBubbleBorderColor: tokens.colors.primary.value,
          valueBubbleColor: tokens.colors.primary.value,
        },
        focused: {
          activeMarkColor: tokens.colors.primary.value,
          activeTrackColor: tokens.colors.primary.value,
          inactiveTrackColor: tokens.colors.neutral["5"],
          labelColor: tokens.colors.primary.value,
          markColor: tokens.colors.neutral["6"],
          thumbBackgroundColor: tokens.colors.surface.elevated.value,
          thumbBorderColor: tokens.colors.primary.value,
          thumbBorderWidth: tokens.borderSize.md,
          thumbHighlightColor: "transparent",
          valueBubbleBackgroundColor: "transparent",
          valueBubbleBorderColor: tokens.colors.primary.value,
          valueBubbleColor: tokens.colors.primary.value,
        },
        disabled: {
          activeMarkColor: tokens.colors.neutral["6"],
          activeTrackColor: tokens.colors.neutral["5"],
          inactiveTrackColor: tokens.colors.neutral["5"],
          labelColor: tokens.colors.text.disabled,
          markColor: tokens.colors.neutral["6"],
          thumbBackgroundColor: tokens.colors.neutral["6"],
          thumbBorderColor: tokens.colors.neutral["6"],
          thumbBorderWidth: tokens.borderSize.md,
          thumbHighlightColor: "transparent",
          valueBubbleBackgroundColor: tokens.colors.neutral["6"],
          valueBubbleBorderColor: tokens.colors.neutral["6"],
          valueBubbleColor: tokens.colors.text.disabled,
        },
      },
      soft: {
        default: {
          activeMarkColor: tokens.colors.primary.value,
          activeTrackColor: tokens.colors.secondary.value,
          inactiveTrackColor: tokens.colors.neutral["5"],
          labelColor: tokens.colors.secondary.contrast,
          markColor: tokens.colors.neutral["6"],
          thumbBackgroundColor: tokens.colors.accent.value,
          thumbBorderColor: tokens.colors.accent.value,
          thumbBorderWidth: tokens.borderSize.sm,
          thumbHighlightColor: tokens.colors.primary.value,
          valueBubbleBackgroundColor: tokens.colors.secondary.value,
          valueBubbleBorderColor: tokens.colors.secondary.value,
          valueBubbleColor: tokens.colors.secondary.contrast,
        },
        focused: {
          activeMarkColor: tokens.colors.primary.value,
          activeTrackColor: tokens.colors.secondary.value,
          inactiveTrackColor: tokens.colors.neutral["5"],
          labelColor: tokens.colors.secondary.contrast,
          markColor: tokens.colors.neutral["6"],
          thumbBackgroundColor: tokens.colors.accent.value,
          thumbBorderColor: tokens.colors.accent.value,
          thumbBorderWidth: tokens.borderSize.sm,
          thumbHighlightColor: tokens.colors.primary.value,
          valueBubbleBackgroundColor: tokens.colors.secondary.value,
          valueBubbleBorderColor: tokens.colors.secondary.value,
          valueBubbleColor: tokens.colors.secondary.contrast,
        },
        disabled: {
          activeMarkColor: tokens.colors.neutral["6"],
          activeTrackColor: tokens.colors.neutral["5"],
          inactiveTrackColor: tokens.colors.neutral["5"],
          labelColor: tokens.colors.text.disabled,
          markColor: tokens.colors.neutral["6"],
          thumbBackgroundColor: tokens.colors.neutral["6"],
          thumbBorderColor: tokens.colors.neutral["6"],
          thumbBorderWidth: tokens.borderSize.sm,
          thumbHighlightColor: "transparent",
          valueBubbleBackgroundColor: tokens.colors.neutral["6"],
          valueBubbleBorderColor: tokens.colors.neutral["6"],
          valueBubbleColor: tokens.colors.text.disabled,
        },
      },
    },
  };
}
