import { ShadowIntensity, ShadowLevel, StyleProps } from "../types";

const StylePropsRecord: Record<keyof StyleProps, number> = {
  margin: 0,
  marginTop: 0,
  marginBottom: 0,
  marginLeft: 0,
  marginRight: 0,
  marginHorizontal: 0,
  marginVertical: 0,
  padding: 0,
  paddingTop: 0,
  paddingBottom: 0,
  paddingLeft: 0,
  paddingRight: 0,
  paddingHorizontal: 0,
  paddingVertical: 0,
  color: 0,
  backgroundColor: 0,
  opacity: 0,
  shadow: 0,
  shadowPosition: 0,
  shadowColor: 0,
  shadowOpacity: 0,
  shadowRadius: 0,
  shadowOffset: 0,
  elevation: 0,
  borderRadius: 0,
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0,
  borderWidth: 0,
  borderTopWidth: 0,
  borderRightWidth: 0,
  borderBottomWidth: 0,
  borderLeftWidth: 0,
  borderColor: 0,
  borderTopColor: 0,
  borderRightColor: 0,
  borderBottomColor: 0,
  borderLeftColor: 0,
  borderStyle: 0,
  fontSize: 0,
  fontFamily: 0,
  fontWeight: 0,
  fontStyle: 0,
  fontVariant: 0,
  letterSpacing: 0,
  lineHeight: 0,
  textAlign: 0,
  textDecorationLine: 0,
  textDecorationStyle: 0,
  textDecorationColor: 0,
  textTransform: 0,
  includeFontPadding: 0,
  textAlignVertical: 0,
  writingDirection: 0,
  flex: 0,
  flexGrow: 0,
  flexShrink: 0,
  flexBasis: 0,
  flexDirection: 0,
  flexWrap: 0,
  justifyContent: 0,
  alignItems: 0,
  alignSelf: 0,
  alignContent: 0,
  gap: 0,
  rowGap: 0,
  columnGap: 0,
  position: 0,
  top: 0,
  right: 0,
  bottom: 0,
  left: 0,
  zIndex: 0,
  width: 0,
  height: 0,
  minWidth: 0,
  maxWidth: 0,
  minHeight: 0,
  maxHeight: 0,
  aspectRatio: 0,
  overflow: 0,
} as const;

export const StylePropsSet = new Set<keyof StyleProps>(
  Object.keys(StylePropsRecord) as (keyof StyleProps)[],
);

export const shadowScale: Record<ShadowLevel, ShadowIntensity> = {
  none: { radius: 0, opacity: 0, elevation: 0 },
  xs: { radius: 2, opacity: 0.08, elevation: 1 },
  sm: { radius: 4, opacity: 0.1, elevation: 2 },
  md: { radius: 8, opacity: 0.15, elevation: 4 },
  lg: { radius: 16, opacity: 0.18, elevation: 8 },
  xl: { radius: 24, opacity: 0.22, elevation: 12 },
};
